import path from "node:path";
import os from "node:os";
import { getIgnoreSessionPrefixesFromEnv } from "./ignore-session.js";
import { envInt } from "./strings.js";
export const DEFAULT_QUEUE = path.join(os.homedir(), ".openclaw", "clawboard-queue.sqlite");
export const SUMMARY_MAX = 72;
export const RAW_MAX = 5000;
export const DEFAULT_CONTEXT_MAX_CHARS = 2200;
export const DEFAULT_CONTEXT_TOPIC_LIMIT = 3;
export const DEFAULT_CONTEXT_LOG_LIMIT = 6;
export const DEFAULT_CONTEXT_FETCH_TIMEOUT_MS = 3000;
export const DEFAULT_CONTEXT_FETCH_RETRIES = 1;
export const DEFAULT_CONTEXT_CACHE_TTL_MS = 45_000;
export const DEFAULT_CONTEXT_CACHE_MAX_ENTRIES = 120;
export const DEFAULT_CONTEXT_CACHE_FRESH_MS = 2500;
export const DEFAULT_POST_TIMEOUT_MS = 8000;
export const DEFAULT_BOARD_SCOPE_CACHE_TTL_MS = 12 * 60 * 60 * 1000;
export const DEFAULT_BOARD_SCOPE_CACHE_MAX_ENTRIES = 4096;
export const CLAWBOARD_CONTEXT_BEGIN = "[CLAWBOARD_CONTEXT_BEGIN]";
export const CLAWBOARD_CONTEXT_END = "[CLAWBOARD_CONTEXT_END]";
export const IGNORE_SESSION_PREFIXES = getIgnoreSessionPrefixesFromEnv(process.env);
/** Longer TTL when resolving subagent scope from DB so long-running subagents stay aligned. Configurable via CLAWBOARD_BOARD_SCOPE_SUBAGENT_TTL_HOURS (default 48). */
export const BOARD_SCOPE_SUBAGENT_PERSISTENCE_TTL_MS = envInt("CLAWBOARD_BOARD_SCOPE_SUBAGENT_TTL_HOURS", 48, 1, 168) * 60 * 60 * 1000;
export const OPENCLAW_REQUEST_ID_PREFIX = "occhat-";
export const OPENCLAW_DAY_SECONDS = 24 * 60 * 60;
export const CLAWBOARD_LOGGER_REGISTERED_SYMBOL = Symbol.for("clawboard.logger.registered");
export const REPLY_DIRECTIVE_TAG_RE = /(?:\[\[\s*(?:reply_to_current|reply_to\s*:\s*[^\]\n]+)\s*\]\]|\[\s*(?:reply_to_current|reply_to\s*:\s*[^\]\n]+)\s*\])\s*/gi;
export const OPENCLAW_REQUEST_ID_TTL_MS = envInt("OPENCLAW_REQUEST_ID_TTL_SECONDS", 7 * OPENCLAW_DAY_SECONDS, 5 * 60, 90 * OPENCLAW_DAY_SECONDS) * 1000;
export const OPENCLAW_REQUEST_ID_MAX_ENTRIES = envInt("OPENCLAW_REQUEST_ID_MAX_ENTRIES", 5000, 200, 50000);
